In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

In [2]:
data_list=[]
#day start/day end/year/place/community/country/hotel/people
#1982
data_list.append([datetime.datetime(1982, 4, 6),datetime.datetime(1982, 4, 11),1982,"Waldshut",'Waldshut-Tiengen',"Germany",'Krankenhaus Waldshut',['Heidrun']])
data_list.append([datetime.datetime(1982, 4, 11),datetime.datetime(1982, 6, 26),1982,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur']])
#check here
data_list.append([datetime.datetime(1982, 6, 26),datetime.datetime(1982, 7, 10),1982,"Gossersweiler",'',"Germany",'',['Heidrun',"Jan-Marc",'Artur']])
data_list.append([datetime.datetime(1982, 7, 10),datetime.datetime(1983, 5, 18),1983,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur']])
data_list.append([datetime.datetime(1983, 5, 18),datetime.datetime(1983, 5, 25),1983,"San Carlos",'',"Spain",'',['Heidrun',"Jan-Marc",'Artur']])
data_list.append([datetime.datetime(1983, 5, 25),datetime.datetime(1985, 6, 26),1984,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur']])
data_list.append([datetime.datetime(1985, 6, 26),datetime.datetime(1985, 7, 9),1985,"Santa Eulalia",'',"Spain",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin']])
data_list.append([datetime.datetime(1985, 7, 9),datetime.datetime(1987, 6, 28),1986,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin']])
data_list.append([datetime.datetime(1987, 6, 28),datetime.datetime(1987, 7, 11),1987,"Calas del Mallorca",'',"Spain",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1987, 7, 11),datetime.datetime(1987, 10, 24),1987,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1987, 10, 24),datetime.datetime(1987, 10, 31),1988,"Flumserberg",'',"Switzerland",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1987, 10, 31),datetime.datetime(1988, 11, 5),1988,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1988, 11, 5),datetime.datetime(1988, 11, 8),1988,"Loerrach",'Loerrach',"Germany","Kinderkrankenhaus Loerrach",['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1988, 11, 8),datetime.datetime(1988, 10, 24),1988,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1988, 10, 24),datetime.datetime(1988, 10, 29),1988,"Beatenberg",'',"Switzerland",'Dorinthotel Beatenberg',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1988, 10, 29),datetime.datetime(1989, 5, 10),1988,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1989, 5, 10),datetime.datetime(1989, 5, 15),1988,"Beatenberg",'',"Switzerland",'Dorinthotel Beatenberg',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1989, 5, 15),datetime.datetime(1989, 6, 20),1989,"Unterlauchringen",'Lauchringen',"Germany",['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1989, 6, 20),datetime.datetime(1989, 6, 27),1988,"Horn",'',"Germany",'Campingplatz Horn',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1989, 6, 27),datetime.datetime(1989, 11, 4),1989,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1989, 11, 4),datetime.datetime(1989, 11, 9),1988,"Missen Willams",'',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1989, 11, 9),datetime.datetime(1990, 5, 25),1990,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1990, 5, 25),datetime.datetime(1990, 6, 8),1990,"San Antonio",'',"Spain",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1990, 6, 8),datetime.datetime(1990, 10, 27),1990,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1990, 10, 27),datetime.datetime(1990, 11, 3),1990,"Lechbruck",'',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1990, 11, 3),datetime.datetime(1991, 5, 18),1991,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1991, 5, 18),datetime.datetime(1991, 6, 1),1991,"Kell am See",'',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1991, 6, 1),datetime.datetime(1991, 8, 3),1991,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1991, 8, 3),datetime.datetime(1991, 8, 13),1991,"Ueberlingen",'',"Germany",'Campingplatz Ueberlingen',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1991, 8, 13),datetime.datetime(1992, 7, 5),1992,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1992, 7, 5),datetime.datetime(1992, 7, 19),1992,"Daun",'',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1992, 7, 19),datetime.datetime(1992, 10, 25),1992,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1992, 10, 25),datetime.datetime(1992, 11, 1),1992,"Lechbruck",'',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1992, 11, 1),datetime.datetime(1993, 10, 30),1993,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1993, 10, 30),datetime.datetime(1993, 11, 6),1993,"Telfs",'',"Austria",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1993, 11, 6),datetime.datetime(1994, 7, 9),1994,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1994, 7, 9),datetime.datetime(1994, 7, 23),1994,"Oberlahr",'',"Germany",'Westerwaldtreff',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1994, 7, 23),datetime.datetime(1994, 10, 27),1994,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1994, 10, 27),datetime.datetime(1994, 11, 2),1994,"Telfs",'',"Austria",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1994, 11, 2),datetime.datetime(1995, 8, 5),1995,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1995, 8, 5),datetime.datetime(1995, 8, 19),1995,"Kirchheim",'',"Germany",'Westerwaldtreff',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1995, 8, 19),datetime.datetime(1996, 5, 5),1996,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1996, 5, 5),datetime.datetime(1996, 5, 6),1996,"Beatenberg",'',"Switzerland",'Dorinthotel Beatenberg',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1996, 5, 6),datetime.datetime(1996, 8, 23),1996,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1996, 8, 23),datetime.datetime(1996, 8, 30),1996,"London",'London',"United Kingdom",'Hotel President',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1996, 8, 30),datetime.datetime(1996, 10, 26),1997,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1996, 10, 26),datetime.datetime(1996, 11, 1),1996,"Stromberg",'',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1996, 11, 1),datetime.datetime(1997, 4, 10),1997,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1997, 4, 10),datetime.datetime(1997, 4, 16),1997,"St Peter Ording",'',"Germany",'',['Schulklasse']])
data_list.append([datetime.datetime(1997, 4, 16),datetime.datetime(1997, 5, 21),1997,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1997, 5, 21),datetime.datetime(1997, 5, 25),1997,"Muenchen",'Muenchen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1997, 5, 25),datetime.datetime(1997, 8, 24),1997,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1997, 8, 24),datetime.datetime(1997, 8, 31),1997,"Rom",'Rom',"Italy",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1997, 8, 31),datetime.datetime(1997, 9, 11),1997,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1997, 9, 11),datetime.datetime(1997, 9, 14),1997,"Steinabad",'Bonndorf',"Germany",'Steinabad',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1997, 9, 14),datetime.datetime(1998, 4, 17),1998,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1998, 4, 17),datetime.datetime(1998, 4, 18),1998,"Ulm",'Ulm',"Germany",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1998, 4, 18),datetime.datetime(1998, 8, 22),1998,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1998, 8, 22),datetime.datetime(1998, 8, 30),1998,"Paris",'Paris',"France",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1998, 8, 30),datetime.datetime(1999, 4, 25),1999,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 4, 25),datetime.datetime(1999, 4, 28),1999,"Bad Honnef",'',"Germany",'',['Schulklasse']])
data_list.append([datetime.datetime(1999, 4, 28),datetime.datetime(1999, 5, 26),1999,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 5, 26),datetime.datetime(1999, 5, 27),1999,"Tiengen",'Waldshut-Tiengen',"Germany",'Chez Schwabe',['Tobias Schwabe',"Stephan Schalk",'Jan Perius','Falko Schmidt',"Alain Lafon",'Anna']])
data_list.append([datetime.datetime(1999, 5, 27),datetime.datetime(1999, 6, 12),1999,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 6, 12),datetime.datetime(1999, 6, 13),1999,"Horheim",'Wutoeschingen',"Germany",'Chez Schalk',['Tobias Schwabe',"Stephan Schalk",'Jan Perius','Falko Schmidt',"Alain Lafon"]])
data_list.append([datetime.datetime(1999, 6, 13),datetime.datetime(1999, 6, 23),1999,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 6, 23),datetime.datetime(1999, 6, 25),1999,"Untermettingen",'',"Germany",'',['Schulklasse']])
data_list.append([datetime.datetime(1999, 6, 25),datetime.datetime(1999, 8, 27),1999,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 8, 27),datetime.datetime(1999, 8, 29),1999,"Athen",'Athen',"Greece",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 8, 29),datetime.datetime(1999, 8, 30),1999,"Nauplia",'Nauplia',"Greece",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 8, 30),datetime.datetime(1999, 8, 31),1999,"Olympia",'Olympia',"Greece",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 8, 31),datetime.datetime(1999, 9, 1),1999,"Delphi",'Delphi',"Greece",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 9, 1),datetime.datetime(1999, 9, 3),1999,"Athen",'Athen',"Greece",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 9, 3),datetime.datetime(1999, 9, 8),1999,"Evia",'Evia',"Greece",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(1999, 9, 8),datetime.datetime(2000, 5, 18),2000,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 5, 18),datetime.datetime(2000, 5, 21),2000,"Muenchen",'Muenchen',"Germany",'',['Hochrheinseminar']])
data_list.append([datetime.datetime(2000, 5, 21),datetime.datetime(2000, 6, 3),2000,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 6, 3),datetime.datetime(2000, 6, 6),2000,"Hannover",'Hannover',"Germany",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 6, 6),datetime.datetime(2000, 7, 9),2000,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 7, 9),datetime.datetime(2000, 7, 10),2000,"Bechtersbohl",'Kuessaberg',"Germany",'',['Schulklasse']])
data_list.append([datetime.datetime(2000, 7, 10),datetime.datetime(2000, 8, 24),2000,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 8, 24),datetime.datetime(2000, 8, 25),2000,"ICE Basel-Frankfurt",'ICE',"Germany",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 8, 25),datetime.datetime(2000, 8, 26),2000,"Antalya",'Antalya',"Turkey",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 8, 26),datetime.datetime(2000, 8, 27),2000,"Bursa",'Bursa',"Turkey",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 8, 27),datetime.datetime(2000, 8, 29),2000,"Istanbul",'Istanbul',"Turkey",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 8, 29),datetime.datetime(2000, 8, 30),2000,"Canakkale",'Canakkale',"Turkey",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 8, 30),datetime.datetime(2000, 8, 31),2000,"Selcuk",'Selcuk',"Turkey",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 8, 31),datetime.datetime(2000, 9, 7),2000,"Kemer",'Kemer',"Turkey",'Kemer Holiday Village',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 9, 7),datetime.datetime(2000, 9, 8),2000,"ICE Frankfurt-Basel",'ICE',"Germany",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2000, 9, 8),datetime.datetime(2001, 4, 19),2001,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 4, 19),datetime.datetime(2001, 4, 20),2001,"Bus Tiengen-Barcelona",'Bus',"Germany",'',["School Outing"]])
data_list.append([datetime.datetime(2001, 4, 20),datetime.datetime(2001, 4, 25),2001,"Barcelona",'Barcelona',"",'',["School Outing"]])
data_list.append([datetime.datetime(2001, 4, 25),datetime.datetime(2001, 4, 26),2001,"Bus Barcelona-Tiengen",'Bus',"",'',["School Outing"]])
data_list.append([datetime.datetime(2001, 4, 26),datetime.datetime(2001, 5, 25),2001,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 5, 25),datetime.datetime(2001, 5, 31),2001,"Berlin",'Berlin',"Germany",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 5, 31),datetime.datetime(2001, 8, 21),2001,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 21),datetime.datetime(2001, 8, 22),2001,"ICE Basel-Frankfurt",'ICE',"Germany",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 22),datetime.datetime(2001, 8, 23),2001,"Malaga",'Malaga',"Spain",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 23),datetime.datetime(2001, 8, 24),2001,"Granada",'Granada',"Spain",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 24),datetime.datetime(2001, 8, 25),2001,"Cordoba",'Cordoba',"Spain",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 25),datetime.datetime(2001, 8, 27),2001,"Sevilla",'Sevilla',"Spain",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 27),datetime.datetime(2001, 8, 28),2001,"Arcos de la Frontera",'Arcos de la Frontera',"Spain",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 28),datetime.datetime(2001, 8, 29),2001,"Ronda",'Ronda',"Spain",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 8, 29),datetime.datetime(2001, 9, 3),2001,"Marbella",'Marbella',"Spain",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 9, 3),datetime.datetime(2001, 9, 4),2001,"ICE Frankfurt-Basel",'ICE',"Germany",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2001, 9, 4),datetime.datetime(2002, 5, 25),2002,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 5, 25),datetime.datetime(2002, 5, 30),2002,"Montainone",'',"Italy",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 5, 30),datetime.datetime(2002, 8, 20),2002,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 8, 20),datetime.datetime(2002, 8, 21),2002,"Agadir",'Agadir',"Morocco",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 8, 21),datetime.datetime(2002, 8, 22),2002,"Marrakesh",'Marrakesh',"Morocco",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 8, 22),datetime.datetime(2002, 8, 24),2002,"Fes",'Fes',"Morocco",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 8, 24),datetime.datetime(2002, 8, 25),2002,"Volubilis",'Volubilis',"Morocco",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 8, 25),datetime.datetime(2002, 8, 26),2002,"Casablanca",'Casablanca',"Morocco",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 8, 26),datetime.datetime(2002, 8, 27),2002,"Eassouira",'Eassouira',"Morocco",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2002, 8, 27),datetime.datetime(2002, 9, 3),2002,"Agadir",'Agadir',"Morocco",'',['Heidrun','Artur','Anne-Kathrin','Hannsjoerg']])
#studium etc check what might have started around the time HERE
data_list.append([datetime.datetime(2002, 9, 3),datetime.datetime(2003, 7, 3),2002,"Unterlauchringen",'Lauchringen',"Germany",'',['Heidrun',"Jan-Marc",'Artur','Anne-Kathrin','Hannsjoerg']])
data_list.append([datetime.datetime(2003, 7, 3),datetime.datetime(2003, 7, 4),2002,"Stuttgart Flughafen",'Stuttgart',"Germany",'',['Sigi',"Gianrico",'Boeni']])


df = pd.DataFrame(data_list,columns=['Date Start','Date End', 'Year','Place', 'Community/City','Country','Hotel','People'])
df["Duration"]=(df['Date End']-df['Date Start'])/np.timedelta64(1,"D")
df.to_csv("../data/NightStays_StationInfo.csv")

In [3]:
df.head()

,Date Start,Date End,Year,Place,Community/City,Country,Hotel,People,Duration
0,1982-04-06,1982-04-11,1982,Waldshut,Waldshut-Tiengen,Germany,Krankenhaus Waldshut,[Heidrun],5.0
1,1982-04-11,1982-06-26,1982,Unterlauchringen,Lauchringen,Germany,,"[Heidrun, Jan-Marc, Artur]",76.0
2,1982-06-26,1982-07-10,1982,Gossersweiler,,Germany,,"[Heidrun, Jan-Marc, Artur]",14.0
3,1982-07-10,1983-05-18,1983,Unterlauchringen,Lauchringen,Germany,,"[Heidrun, Jan-Marc, Artur]",312.0
4,1983-05-18,1983-05-25,1983,San Carlos,,Spain,,"[Heidrun, Jan-Marc, Artur]",7.0

In [4]:
df.groupby('Place').agg(Nights=("Duration",'sum')).sort_values(by="Nights",ascending=False).head(25)

                    Nights
Place
Unterlauchringen    7437.0
Kirchheim             14.0
Daun                  14.0
San Antonio           14.0
Oberlahr              14.0
Lechbruck             14.0
Kell am See           14.0
Gossersweiler         14.0
Telfs                 13.0
Santa Eulalia         13.0
Calas del Mallorca    13.0
Beatenberg            11.0
Ueberlingen           10.0
Paris                  8.0
Agadir                 8.0
Kemer                  7.0
San Carlos             7.0
Flumserberg            7.0
Rom                    7.0
Muenchen               7.0
Horn                   7.0
London                 7.0
Stromberg              6.0
St Peter Ording        6.0
Berlin                 6.0

In [5]:
datetime.datetime(2003, 7, 4)-datetime.datetime(1982,7, 3)

datetime.timedelta(days=7671)

In [6]:
    df.loc[(df["Date Start"]-df['Date End'].shift(1))!=np.timedelta64(0,'D'),"Date Start"]

0   1982-04-06
Name: Date Start, dtype: datetime64[ns]